Web/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  #root to: 'couch_posts#show'
  get '/my_couch_posts' => 'couch_posts#mycouchposts', as: 'my_couch_posts'
  get '/visited_couch_posts' => 'couch_posts#visitedcouchposts', as: 'visited_couch_posts'
  get '/main_pic_edit/:id', to: 'couch_posts#mainpicedit', as: 'main_pic_edit'
  get '/foreign_requests_index' => 'couch_reservation_requests#foreign_requests_index', as: 'foreign_requests_index'
  get '/couch_reservation_requests/date_filter_results' => 'couch_reservation_requests#date_filter_results', as: 'date_filter_results'
  match 'couch_reservation_requests/respond', to: 'couch_reservation_requests#respond', via: 'post'
  match 'user_premium/setpaid', to: 'user_premium#setpaidform', via: 'get', as: :setpaidform
  match 'user_premium/setpaid', to: 'user_premium#setpaid', via: 'post', as: :setpaid
  
  match 'user_premium/getpaid', to: 'user_premium#getpaidform', via: 'get', as: :getpaidform
  match 'user_premium/getpaid', to: 'user_premium#getpaid', via: 'post', as: :getpaid


  devise_for :users
  resources :users
  resources :couch_types
  resources :couch_posts
  resources :couch_post_feedbacks
  resources :couch_reservation_requests
  resources :user_feedbacks
  resources :user_premium 
end

Web/app/controllers/couch_types_controller.rb
class CouchTypesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def new
    @couch_type = CouchType.new
    authorize CouchType
  end

  def index
  	@couch_types = CouchType.all
    authorize CouchType
  end

  def create
    authorize CouchType
    parameters = params.require(:couch_type).permit(:name,:disabled)
    @couch_type = CouchType.new(parameters)
    if @couch_type.save
      redirect_to couch_types_path , notice: "Tipo creado."
    else
      redirect_to couch_types_path , alert: "No se pudo crear tipo: " << @couch_type.errors.full_messages.to_sentence
    end
  end

  def edit
    authorize CouchType
    @couch_type = CouchType.find(params[:id])
  end

  def update
    authorize CouchType
    
    @couch_type = CouchType.find(params[:id]) 
    if @couch_type.update(params.require(:couch_type).permit(:name,:disabled))
      redirect_to couch_types_path , notice: "Tipo actualizado"
    else
      redirect_to couch_types_path , alert: "Error al actualizar: " << @couch_type.errors.full_messages.to_sentence
    end
  end

  def destroy
    authorize CouchType

    @couch_type = CouchType.find(params[:id])
    if @couch_type.destroy
      redirect_to couch_types_path , notice: "Tipo eliminado"
    else
      redirect_to couch_types_path , alert: "Error al eliminar" << @couch_type.errors.full_messages.to_sentence
    end
  end
end

Web/app/views/couch_types/_couch_type.html.erb
<td class="col-md-9 text-left">
  <% if couch_type.disabled? %>
      <div class="text-muted"><%= couch_type.name.capitalize %> (Deshabilitado)</div>
  <% else %>
      <%= couch_type.name.capitalize %>
  <% end %>
</td>

<td class="col-md-1 text-center">
  <% if couch_type.couch_posts.empty?%>
  <%= link_to("Eliminar", couch_type_path(couch_type), :data => { :confirm => "¿Estás seguro/a?" }, :method => :delete, :class => 'btn btn-danger btn-xs') %>
  <% end %>
</td>

<% if couch_type.disabled %>
  <td class="col-md-1 text-center">
    <%= form_for couch_type do |t| %>
      <%= t.hidden_field :disabled, value: :false %>
      <%= t.submit "Habilitar", :class => 'btn btn-success btn-xs'%>
    <% end %>
  </td>
<% else %>
  <td class="col-md-1 text-center">
    <%= form_for couch_type do |t| %>
      <%= t.hidden_field :disabled, value: :true %>
      <%= t.submit "Deshabilitar", :class => 'btn btn-xs'%>
    <% end %>
  </td>
<% end %>

<td class="col-md-1 text-center">
  <%= link_to("Modificar", edit_couch_type_path(couch_type), :method => :get, :class => 'btn btn-info btn-xs') %>
</td>

Web/app/views/couch_types/_couch_types_side.html.erb
<div class="col-md-3">
    <a href="/"><img class="lead"  src="<%= asset_path('logo.png') %>" alt=""></a>
    <div class="list-group">
      <% if @showingall.present? and @showingall == true %>
        <%= link_to("Ver todos", couch_posts_path + "?s=" + (params[:s].presence || ''), :class => "list-group-item active") %>
      <% else %>
        <%= link_to("Ver todos", couch_posts_path + "?s=" + (params[:s].presence || ''), :class => "list-group-item") %>
      <% end %>
      <% CouchType.all.each do |couch_type| %>
        <% if @category.present? and @category == couch_type %>
          <%= link_to(couch_type.name.capitalize, couch_posts_path + "?cat=" + couch_type.name + "&s=" + (params[:s].presence || ''), :class => "list-group-item active") %>
        <% else %>
          <%= link_to(couch_type.name.capitalize, couch_posts_path + "?cat=" + couch_type.name + "&s=" + (params[:s].presence || ''), :class => "list-group-item") %>
        <% end %>
      <% end %>
    </div>
</div>

Web/app/views/couch_types/_form.html.erb
<%= form_for(@couch_type) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :required => true, :autofocus => true, class: 'form-control' %>
    <br>
    <%= f.hidden_field :disabled , value:false %>
  </div>
  <%= f.submit 'Guardar', class: 'button right' %>
 <% end %>

Web/app/views/couch_types/edit.html.erb
<div class="authform">
  <h3>Editar tipo de Couch</h3>
  	<%= render 'form' %>
</div>

Web/app/views/couch_types/index.html.erb
<div class="container">
    <h3>Tipos de Couches</h3>
    <table class="table table-striped">
        <tbody>
            <% @couch_types.each do |couch_type| %>
                <tr>
                    <%= render couch_type %>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to("Crear nuevo tipo de Couch", new_couch_type_path , :class => 'button-xs')%>
</div>

Web/app/views/couch_types/new.html.erb
<div class="authform">
  <h3>Nuevo tipo de Couch</h3>
  	<%= render 'form' %>
</div>