Web/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  #root to: 'couch_posts#show'
  get '/my_couch_posts' => 'couch_posts#mycouchposts', as: 'my_couch_posts'
  get '/visited_couch_posts' => 'couch_posts#visitedcouchposts', as: 'visited_couch_posts'
  get '/main_pic_edit/:id', to: 'couch_posts#mainpicedit', as: 'main_pic_edit'
  get '/foreign_requests_index' => 'couch_reservation_requests#foreign_requests_index', as: 'foreign_requests_index'
  get '/couch_reservation_requests/date_filter_results' => 'couch_reservation_requests#date_filter_results', as: 'date_filter_results'
  match 'couch_reservation_requests/respond', to: 'couch_reservation_requests#respond', via: 'post'
  match 'user_premium/setpaid', to: 'user_premium#setpaidform', via: 'get', as: :setpaidform
  match 'user_premium/setpaid', to: 'user_premium#setpaid', via: 'post', as: :setpaid
  
  match 'user_premium/getpaid', to: 'user_premium#getpaidform', via: 'get', as: :getpaidform
  match 'user_premium/getpaid', to: 'user_premium#getpaid', via: 'post', as: :getpaid


  devise_for :users
  resources :users
  resources :couch_types
  resources :couch_posts
  resources :couch_post_feedbacks
  resources :couch_reservation_requests
  resources :user_feedbacks
  resources :user_premium 
end

Web/app/models/couch_post.rb
class CouchPost < ActiveRecord::Base
  ratyrate_rateable "rating"
  belongs_to :couch_type
  belongs_to :user
  has_many :couch_reservation_requests
  has_many :couch_post_feedbacks

  has_attached_file :mainpic, styles: { frontpage: "320x150#", couchlist: "300x240#", bigpanoramic: "800x300#"}, default_url: "images/:style/missing.png"
  validates_presence_of :couch_type
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :rooms
  validates_presence_of :vacants
  validates_presence_of :zone
  validates_attachment_content_type :mainpic, :content_type =>["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def is_owner?(user)
    return self.user_id = user.id
  end
  

  def is_free?(from, to)
    reservas_del_couch = self.couch_reservation_requests
    reservas_confirmadas = reservas_del_couch.confirmed
    
    return reservas_confirmadas.where('end_date >= ? AND start_date <= ?', from,to).empty?
  end
  

  def self.free_couches(from, to)
    result = [] 
    Couch.all.each do |couch|
      result << couch if couch.is_free?(from, to)
    end
  end
end

Web/app/controllers/couch_posts_controller.rb
class CouchPostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  after_action :verify_authorized, :except => [:index]



  def new
    @couch_post = CouchPost.new
    authorize CouchPost
  end

  def create
    authorize CouchPost
    @couch_post = CouchPost.create(couch_post_params)
    if @couch_post.valid?
      redirect_to @couch_post, :notice => "Aviso creado."
    else
      redirect_to new_couch_post_path, :alert => "No se pudo crear el couch. " << @couch_post.errors.full_messages.to_sentence
    end
  end

  def index
    @couch_posts = CouchPost.joins('LEFT OUTER JOIN users ON couch_posts.user_id = users.id').order('users.premium_expiration IS NULL, users.premium_expiration DESC')
    @showingall = true

    if params[:s].present?
      @couch_posts = @couch_posts.where("LOWER(title) LIKE ? OR LOWER(description) LIKE ?", "%#{params[:s].downcase}%", "%#{params[:s].downcase}%")
      @filter_text = "Buscando \"#{params[:s]}\" "
    else
      @filter_text = "Mostrando todos "
    end
    if params[:cat].present?
      @category = CouchType.where(name: params[:cat]).first
      if @category.present?
        @couch_posts = @couch_posts.where({couch_type: @category })
        @filter_text += "del tipo #{@category.name.capitalize}"
        @showingall = false
      end
    end
    @couch_posts = @couch_posts.paginate(:page => params[:page], :per_page => 5)
  end

  def mycouchposts
    authorize CouchPost
    @my_couch_posts = CouchPost.where(user_id: current_user.id)
  end

    def visitedcouchposts
    authorize CouchPost
    couch_reqs= CouchReservationRequest.requests_made_by_user(current_user.id)
    couch_reqs= couch_reqs.where(accepted: true)
      @visited_couch_posts = Array.new
      couch_reqs.each do |r|
        if(r.start_date < Date.today)
        c= CouchPost.find(r.couch_post_id)
        @visited_couch_posts << c
      end
      end
   
   
   end

  def show
    authorize CouchPost
  	@couch_post = CouchPost.find(params[:id])
    @category = @couch_post.couch_type
    @couch_post_feedbacks = CouchPostFeedback.where(couch_post_id: @couch_post.id)
    @couch_post_feedback_val = 0
    if @couch_post_feedbacks.count > 0
      @couch_post_feedback_scored = 0
         @couch_post_feedbacks.each do |feed| 
          if(feed.score != nil)
          @couch_post_feedback_val =  @couch_post_feedback_val + feed.score
            @couch_post_feedback_scored += 1
          end
         end 
        if (@couch_post_feedback_scored > 0)
           @couch_post_feedback_val =  @couch_post_feedback_val / @couch_post_feedback_scored
        end
    end 
  end

  def destroy
    authorize CouchPost
    couch_post = CouchPost.find(params[:id])
    couch_post.destroy!
    redirect_to my_couch_posts_path , notice: "Couch eliminado"
  end

  def update
    authorize CouchPost
    @id_a_cambiar = params[:id]
    @couch_post = CouchPost.find(params[:id])

    
      @couch_post.update_attributes(params.require(:couch_post).permit(:id, :title, :couch_type_id, :description, :rooms, :vacants, :mainpic, :zone))
      if @couch_post.valid?
        redirect_to my_couch_posts_path , notice: "Post actualizado"
      else
        redirect_to my_couch_posts_path , notice: "Error al actualizar" 
      end

  end




  def edit
        authorize CouchPost
    @couch_post = CouchPost.find(params[:id])
    @id_a_cambiar = params[:id]
  end

  def mainpicedit
    authorize CouchPost
    @couch_post = CouchPost.find(params[:id])
    @id_a_cambiar = params[:id]
  end

  def mainpicupdate
  authorize CouchPost
  @id_a_cambiar = params[:id]
  @couch_post = CouchPost.find(params[:id])
  @couch_post.update_attributes(params.require(:couch_post).permit(:id, :mainpic))
      if @couch_post.valid?
        redirect_to my_couch_posts_path , notice: "Imagen actualizada"
      else
        redirect_to my_couch_posts_path , notice: "Error al actualizar" 
      end

  end

  private
  def couch_post_params
  	params.require(:couch_post).permit(:title, :description, :couch_type_id, :user_id, :zone, :rooms, :vacants, :mainpic)
  end
end

Web/app/helpers/couch_post_helper.rb
module CouchPostHelper
end

Web/app/views/couch_posts/_couch_post.html.erb
<div class="panel panel-body">
    <% @couch_post_feedbacks = CouchPostFeedback.where(couch_post_id: couch_post.id)  %>
   <%    @couch_post_feedback_val = 0  %>
   <%    if @couch_post_feedbacks.count > 0  %>
   <%         @couch_post_feedback_scored = 0 %>
   <%         @couch_post_feedbacks.each do |feed|   %>
   <%  if(feed.score != nil) %>
    <%         @couch_post_feedback_val =  @couch_post_feedback_val + feed.score  %>
    <%   @couch_post_feedback_scored += 1 %>
    <%        end   %>
      <%        end   %>
       <%   if (@couch_post_feedback_scored > 0)  %>
    <%         @couch_post_feedback_val =  @couch_post_feedback_val / @couch_post_feedback_scored   %>
    <% end %>
      <% end %>


    <div class="row">
        <div class="col-md-4">
            <%= link_to(couch_post_path(couch_post.id), :method => :get) do%>
              <% if couch_post.user.is_premium? then %>
                <img class="img-responsive" src= <%=couch_post.mainpic.url(:couchlist)%> alt="">
              <% else %>
                <img class="img-responsive" src="/images/couchlist/missing.png" alt="">
              <% end %>
            <% end %>
        </div>
        <div class="col-md-8">
            <h3><%= link_to couch_post.title, couch_post_path(couch_post.id) %></h3>
            <h4><%= link_to couch_post.user.name, user_path(couch_post.user) %></h4>
            <p class="truncate-post"><%= couch_post.description %> </p>
            <div class="row">
                <div class="col-md-5">
                    <div class="ratings-list">
                         <p class="pull-right">
                           <%= @couch_post_feedbacks.count%> comentario<% if(@couch_post_feedbacks.count != 1)%>s<%end%>
                         </p>
                         <p> 
                            <% (1..5).each do |i| %>
                                <%  @couch_post_feedback_val ||= 0 %>
                                <% if( i <=  @couch_post_feedback_val)%> 
                                  <span class="glyphicon glyphicon-star"></span>
                                <% else %>
                                  <span class="glyphicon glyphicon-star-empty"></span>
                                <% end %>     
                            <% end %>       
                         </p>
                    </div>
                </div>

                <div class="col-md-7">
                  <%= link_to(couch_post_path(couch_post.id), :method => :get, :class => 'btn btn-primary pull-right') do%>
                     Ver Couch<span class="glyphicon glyphicon-chevron-right"></span>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

Web/app/views/couch_posts/_form.erb
<div class="authform">
	<h3>Actualizar Couch</h3>

	<%= form_for :couch_post, url: couch_posts_path do |c| %>
	<div class="form-group">
		<%= c.label :title %>
		<%= c.text_field :title, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :description %>
		<%= c.text_area :description, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :couch_type_id %>
		<%= c.collection_select( :couch_type_id, CouchType.all.where(disabled: false) , :id, :name_for_select, {:prompt => 'Elegí una categoría'}, {:required => true}) %>
	</div>



	<div class="form-group">
		<%= c.label :zone %>
		<%= c.text_field :zone, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :rooms %>
		<%= c.number_field :rooms, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :vacants %>
		<%= c.number_field :vacants, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group" >
	
		<%= c.hidden_field :user_id, value: @current_user.id %>
	</div>

	<div class="form-group">
		<%= c.label :mainpic %>
		<%= c.file_field :mainpic, required: :true, class: 'form-control' %>
	</div>

	<%= c.submit 'Publicar Couch', :class => 'button right' %>
	<% end %>
</div>

Web/app/views/couch_posts/_my_couch_post.html.erb
    <div class="panel panel-default">
      <div class="panel-heading"><h4><%= link_to my_couch_post.title, couch_post_path(my_couch_post.id) %></h4></div>
         <div class="panel-body">
Descripción: <%= my_couch_post.description %>
<br>
Tipo: <%= CouchType.find(my_couch_post.couch_type_id).name.capitalize %>
<br>
Zona: <%= my_couch_post.zone %>
<br>
Habitaciones: <%= my_couch_post.rooms %>
<br>
Vacantes: <%= my_couch_post.vacants %>
<br>



  <div class="btn-group pull-right">
            <a href= <%= edit_couch_post_path(my_couch_post)%> class='btn btn-info btn-xs pull-left'>Modificar</a>
     
         <%= link_to("Cambiar Imagen", main_pic_edit_path(my_couch_post), :class => 'btn btn-success btn-xs pull-left') %>

  	 <% if my_couch_post.couch_reservation_requests.where(accepted: nil).empty?%>
  <%= link_to("Eliminar", couch_post_path(my_couch_post), :data => { :confirm => "¿Estás seguro/a?" }, :method => :delete, :class => 'btn btn-danger btn-xs pull-left') %>
  	  <% end %>

</div>
</div>
</div>
</div>

Web/app/views/couch_posts/edit.html.erb
<div class="authform">
	<h3>Modificar Couch</h3>

	<%= form_for @couch_post, :html => { :multipart => true }  do |c| %>
	<div class="form-group">
		<%= c.label :title %>
		<%= c.text_field :title, required: :true , class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :description %>
		<%= c.text_area :description, required: :true,class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :couch_type_id %>
		<%= c.collection_select(:couch_type_id, CouchType.all.where(disabled: false), :id, :name_for_select, {:required => true , class: "form-control"}) %>
	</div>



	<div class="form-group">
		<%= c.label :zone %>
		<%= c.text_field :zone, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :rooms %>
		<%= c.number_field :rooms, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :vacants %>
		<%= c.number_field :vacants, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group" >
	
		<%= c.hidden_field :user_id %>
	</div>

		<div class="form-group" >
	
		<%= c.hidden_field :id %>
	</div>

	<%= c.submit 'Modificar Couch', :class => 'button left' %>
	 <%= link_to("Volver", my_couch_posts_path, :class => 'btn btn-danger pull-right') %>
	<% end %>
</div>

Web/app/views/couch_posts/index.html.erb
<div class="container">
    <div class="row">

    <%= render 'couch_types/couch_types_side' %>

    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <h1 >Couches disponibles
                    <small><%= @filter_text %></small>
                </h1>
            </div>
        </div>

        <% @couch_posts.each do |couch_post| %>
            <%= render couch_post %>
        <% end %>

        <div class="row text-center">
          <div class="col-lg-12">
            <ul class="pagination">
              <%= will_paginate @couch_posts, renderer: BootstrapLinkRenderer, container: false, previous_label: '&laquo;', next_label: '&raquo;' %>
            </ul>
          </div>
        </div>

        <div class="row text-center">
          <%= link_to("Publicar Couch", new_couch_post_path , :class => 'btn btn-success btn-lg pull-right post-couch')%>
        </div>
        <hr>

    </div>
    </div>
</div>

Web/app/views/couch_posts/mainpicedit.html.erb
<div class="authform">


	<%= form_for @couch_post, :html => { :multipart => true }  do |c| %>
		<h3><%= @couch_post.title %></h3>

<h4>Imagen actual</h4>

    <div>
     <img class="img-responsive" src="<%= @couch_post.mainpic.url %>" alt="">
	</div>

	<div class="form-group">
		<%= c.label :mainpic %>
		<%= c.file_field :mainpic, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group" >
	
		<%= c.hidden_field :user_id %>
	</div>

		<div class="form-group" >
	
		<%= c.hidden_field :id %>
	</div>

	<%= c.submit 'Modificar Couch', :class => 'button left' %>
	 <%= link_to("Volver", my_couch_posts_path, :class => 'btn btn-danger pull-right') %>
	<% end %>

</div>

Web/app/views/couch_posts/my_couch_posts.html.erb
<div class="container">
    <div class="row">
    
    <%= render 'couch_types/couch_types_side' %>

    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <h1 >Couches disponibles
                    <small>Mostrando todos</small>
                </h1>
            </div>
        </div>

        <% @couch_posts.each do |couch_post| %>
            <%= render couch_post %>
        <% end %>

        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row text-center">
          <%= link_to("Publicar Couch", new_couch_post_path , :class => 'btn btn-success btn-lg pull-right post-couch')%>
        </div>
        <hr>

    </div>
    </div>
</div>

Web/app/views/couch_posts/mycouchposts.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <h1 >Mis Couches</h1>
            </div>
        </div>
 <table class="table table-striped">
    <tbody>
        <div class="panel-group">
           <% @my_couch_posts.each do |own_couch_post| %>
       <%= render partial: "my_couch_post", object: own_couch_post  %>
        <% end %>
         </div>
  </tbody>
  </table>
      
        <div class="row text-center">
          <td class="col-md-1 text-center">
                    <%= link_to("Volver", root_path , :class => 'btn btn-danger btn-lg pull-right post-couch')%>
                  </td>
                    <td class="col-md-1 text-center">
          <%= link_to("Publicar Couch", new_couch_post_path , :class => 'btn btn-success btn-lg pull-right post-couch')%>
          </td>
        </div>
        <hr>

    </div>
    </div>
</div>

Web/app/views/couch_posts/new.html.erb
<div class="authform">
	<h3>Publicar Couch</h3>

	<%= form_for :couch_post, url: couch_posts_path do |c| %>
	<div class="form-group">
		<%= c.label :title %>
		<%= c.text_field :title, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :description %>
		<%= c.text_area :description, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :couch_type_id %>
		<%= c.collection_select(:couch_type_id, CouchType.all.where(disabled: false), :id, :name_for_select, {prompt: 'Elegí una categoría', class: "form-control"}, {:required => true, class: "form-control"}) %>
	</div>



	<div class="form-group">
		<%= c.label :zone %>
		<%= c.text_field :zone, required: :true, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :rooms %>
		<%= c.number_field :rooms, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :vacants %>
		<%= c.number_field :vacants, required: :true, min: 1, class: 'form-control' %>
	</div>

	<div class="form-group" >
	
		<%= c.hidden_field :user_id, value: @current_user.id %>
	</div>

	<div class="form-group">
		<%= c.label :mainpic %>
		<%= c.file_field :mainpic, required: :true, class: 'form-control' %>
	</div>

	<%= c.submit 'Publicar Couch', :class => 'button right' %>
	<% end %>
</div>

Web/app/views/couch_posts/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'couch_types/couch_types_side' %>
    <div class="col-md-9">
      <div class="thumbnail">
        <img class="img-responsive" src="<%= @couch_post.mainpic.url(:bigpanoramic) %>" alt="">
        <div class="caption-full">
          <h2><a href="#"><%= @couch_post.title if @couch_post.title %></a></h2>
          <h4><%= link_to @couch_post.user.name, user_path(@couch_post.user) %></h4>
          <p><%= @couch_post.description if @couch_post.description %></p>
          <p>Tipo: <%= CouchType.find(@couch_post.couch_type_id).name.capitalize if @couch_post.couch_type_id %> </p>
          <p>Zona: <%= @couch_post.zone if @couch_post.zone %></p>
          <p>Cantidad de habitaciones: <%= @couch_post.rooms if @couch_post.rooms %></p>
          <p>Cantidad de lugares disponibles: <%= @couch_post.vacants if @couch_post.vacants %></p>
        </div>
        <div class="ratings">
          <p class="pull-right">
            <%= @couch_post_feedbacks.count%> comentario<% if(@couch_post_feedbacks.count != 1)%>s<%end%>
          </p>
          <p> 
            <%= render partial: "stars", locals: {rating_value: @couch_post_feedback_val} %>
          </p>
        </div>
      </div>
      <div class="well">
        <div class="row hidden-xs">
          <div class="col-md-12">
            <%= link_to "Reservar", {controller: 'couch_reservation_requests', action: 'new' , couch_post_id: @couch_post.id.to_s },class: 'btn btn-primary' %>
            <%= link_to "¿Visitaste este Couch? ¡Deja un comentario!", {controller: 'couch_post_feedbacks', action: 'new' , couch_post_id: @couch_post.id },class: 'btn btn-success' %>
            <%= link_to "Reportar Publicación", {controller: 'couch_post_feedbacks', action: 'new' , couch_post_id: @couch_post.id },class: 'btn btn-danger' %>
          </div>
        </div>
        <div class="row hidden-sm hidden-md hidden-lg">
          <div class="col-md-12">
            <ul class="list-unstyled">
            <li>
              <%= link_to "Reservar", {controller: 'couch_reservation_requests', action: 'new' , couch_post_id: @couch_post.id.to_s },class: 'btn btn-primary mobile-button' %>
            </li>
            <li>
                <%= link_to "Comentar", {controller: 'couch_post_feedbacks', action: 'new' , couch_post_id: @couch_post.id }, class: 'btn btn-success mobile-button' %>
            </li>
            <li>
              <a class="btn btn-danger mobile-button">Reportar Publicación</a>
            </li>
          </div>
        </div>

          <% @couch_post_feedbacks.each do |cpf| %>

        <hr>
        <div class="row">
          <div class="col-md-12">
             <p> 
            <%= render partial: "stars", locals: {rating_value: cpf.score} %>
          </p>
          <%= User.find(cpf.user_id).name %>
           <% if(Time.now.to_date - cpf.created_at.to_date <= 0)%>  <span class="pull-right"> Hace unos minutos </span> <%end%>
             <% if(Time.now.to_date - cpf.created_at.to_date > 0)%> <span class="pull-right">Hace <%= (Time.now.to_date - cpf.created_at.to_date).to_i %> día<% if( (Time.now.to_date - cpf.created_at.to_date).to_i != 1)%>s<%end%></span> <%end%>
            
            <p> <%= cpf.comment %></p>
          </div>
        </div>
         <% end %>

      </div>
    </div>
  </div>
</div>

Web/app/views/couch_posts/visitedcouchposts.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <h1 >Couches visitados</h1>
            </div>
        </div>
 <table class="table table-striped">
    <tbody>
        <div class="panel-group">
          <% @visited_couch_posts.each do |couch_post| %>
      <%= render partial: "couch_post", object: couch_post  %>
        <% end %>
         </div>
  </tbody>
  </table>
      
        <div class="row text-center">
          <td class="col-md-1 text-center">
                    <%= link_to("Volver", root_path , :class => 'btn btn-danger btn-lg pull-right post-couch')%>
                  </td>
                 
        </div>
        <hr>

    </div>
    </div>
</div>