Web/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  #root to: 'couch_posts#show'
  get '/my_couch_posts' => 'couch_posts#mycouchposts', as: 'my_couch_posts'
  get '/visited_couch_posts' => 'couch_posts#visitedcouchposts', as: 'visited_couch_posts'
  get '/main_pic_edit/:id', to: 'couch_posts#mainpicedit', as: 'main_pic_edit'
  get '/foreign_requests_index' => 'couch_reservation_requests#foreign_requests_index', as: 'foreign_requests_index'
  get '/couch_reservation_requests/date_filter_results' => 'couch_reservation_requests#date_filter_results', as: 'date_filter_results'
  match 'couch_reservation_requests/respond', to: 'couch_reservation_requests#respond', via: 'post'
  match 'user_premium/setpaid', to: 'user_premium#setpaidform', via: 'get', as: :setpaidform
  match 'user_premium/setpaid', to: 'user_premium#setpaid', via: 'post', as: :setpaid
  
  match 'user_premium/getpaid', to: 'user_premium#getpaidform', via: 'get', as: :getpaidform
  match 'user_premium/getpaid', to: 'user_premium#getpaid', via: 'post', as: :getpaid


  devise_for :users
  resources :users
  resources :couch_types
  resources :couch_posts
  resources :couch_post_feedbacks
  resources :couch_reservation_requests
  resources :user_feedbacks
  resources :user_premium 
end

Web/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Web/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

Web/app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to 'Ver Couches', couch_posts_path %></li>
  <li><%= link_to 'Publicar Couch', new_couch_post_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.try(:name) %> <span class="glyphicon glyphicon-user"></span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Perfil', user_path(current_user) %></li>
        <li><%= link_to 'Cuenta', edit_user_registration_path %></li>
        <li><%= link_to 'Mis reservas', couch_reservation_requests_path %></li>
        <li><%= link_to 'Solicitudes', '/foreign_requests_index' %></li>
        <li><%= link_to 'Mis Couches', my_couch_posts_path %></li>
        <li><%= link_to 'Mis Calificaciones', user_feedbacks_path %></li>
        <li><%= link_to 'Comprar Premium', user_premium_index_path %></li>
        <% if current_user.try(:admin?) %>
          <li><%= link_to 'Usuarios', users_path %></li>
          <li><%= link_to 'Tipos de Couches', couch_types_path %></li>
          <li><%= link_to 'Calcular Ingresos', getpaidform_path%></li>
          <li><%= link_to 'Simular Pagos', setpaidform_path %></li>
          <li><%= link_to 'Upmin', '/admin' %></li>
        <% end %>
        <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method=>'delete'%></li>
      </ul>
    </li>

  <% else %>
  <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
  <li><%= link_to 'Registrarse', new_user_registration_path %></li>
  <% end %>
</ul>

<form class="navbar-form" role="search" action="/couch_posts" method="get">
  <div class="form-group" style="display:inline;">
    <div class="input-group" style="display:table;">
      <% if @category.present? %>
        <input type="hidden" name="cat" id="cat" value="<%= @category.name %>">
        <input class="form-control" name="s" placeholder="Buscar Couches del tipo <%= @category.name.capitalize %>..." autocomplete="off" value="<%= params[:s]%>" autofocus="autofocus" onfocus="this.value = this.value;" type="text">
      <% else %>
        <input class="form-control" name="s" placeholder="Buscar Couches..." autocomplete="off" value="<%= params[:s]%>" autofocus="autofocus" onfocus="this.value = this.value;" type="text">
      <% end %>
      <div class="input-group-btn" style="width:1%;">
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </div>
    </div>
  </div>
</form>

Web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CouchInn" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CouchInn" %>">
    <link rel="shortcut icon" href="assets/icon.png"/>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <div class="container">

      <hr>

      <!-- Footer -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; CouchInn 2015</p>
          </div>
        </div>
      </footer>

      </div>

    </main>
  </body>
</html>