Web/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  #root to: 'couch_posts#show'
  get '/my_couch_posts' => 'couch_posts#mycouchposts', as: 'my_couch_posts'
  get '/visited_couch_posts' => 'couch_posts#visitedcouchposts', as: 'visited_couch_posts'
  get '/main_pic_edit/:id', to: 'couch_posts#mainpicedit', as: 'main_pic_edit'
  get '/foreign_requests_index' => 'couch_reservation_requests#foreign_requests_index', as: 'foreign_requests_index'
  get '/couch_reservation_requests/date_filter_results' => 'couch_reservation_requests#date_filter_results', as: 'date_filter_results'
  match 'couch_reservation_requests/respond', to: 'couch_reservation_requests#respond', via: 'post'
  match 'user_premium/setpaid', to: 'user_premium#setpaidform', via: 'get', as: :setpaidform
  match 'user_premium/setpaid', to: 'user_premium#setpaid', via: 'post', as: :setpaid
  
  match 'user_premium/getpaid', to: 'user_premium#getpaidform', via: 'get', as: :getpaidform
  match 'user_premium/getpaid', to: 'user_premium#getpaid', via: 'post', as: :getpaid


  devise_for :users
  resources :users
  resources :couch_types
  resources :couch_posts
  resources :couch_post_feedbacks
  resources :couch_reservation_requests
  resources :user_feedbacks
  resources :user_premium 
end

Web/app/models/user_premium.rb
class UserPremium < ActiveRecord::Base

end

Web/app/controllers/user_premium_controller.rb
class UserPremiumController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  
  def index
    authorize UserPremium
  end
  
  def getpaid
    authorize UserPremium
    if params.has_key?(:dates) then
      begin
        @sdate = Date.parse(params[:dates][:start_date])
        @edate = Date.parse(params[:dates][:end_date])
      rescue
        redirect_to getpaidform_path, alert: "Debes ingresar dos fechas validas"
      else
        if @sdate > @edate then
          redirect_to getpaidform_path, alert: "La fecha fi no puede ser anterior a la fecha inicio"
        else
          income = UserPremium.where('paidtime >= ? AND paidtime <= ?', @sdate, @edate).count * 100        
          redirect_to getpaidform_path, notice: "Los ingresos entre #{@sdate} y #{@edate} fueron de $#{income}" 
        end
      end
    else
      redirect_to getpaidform_path, alert: "Debes ingresar dos fechas"
    end

  end
  
  def getpaidform
    authorize UserPremium
  end
  
  def setpaid
    authorize UserPremium
    cid = params[:id].to_i
    if cid == 0 then
      redirect_to setpaidform_path, alert: "ID inválido" 
    else
      coupon = UserPremium.where(coupon_id: cid).first
      if coupon.nil? then
        redirect_to setpaidform_path, alert: "ID inexistente" 
      else
        if coupon.paid == true then
          redirect_to setpaidform_path, alert: "Boleta ya paga"
        else
          coupon.paid = true
          coupon.paidtime = DateTime.current
          coupon_user = User.find(coupon.user_id)
          coupon.save
          
          if coupon_user.is_premium? then
            coupon_user.premium_expiration = coupon_user.premium_expiration + 1.months
          else
            coupon_user.premium_expiration = DateTime.current + 1.months
          end
          coupon_user.save
          
          redirect_to setpaidform_path, notice: "Se marcó exitosamente como paga la boleta de #{coupon_user.name}"
        end
      end
    end
  end
  
  def setpaidform
      authorize UserPremium
  end
  
  def create
    authorize UserPremium
    user_premium = UserPremium.new
    user_premium.user_id = current_user.id
    maxcoupon = UserPremium.maximum("coupon_id")
    if maxcoupon.nil? then
      maxcoupon = 0
    end
    maxcoupon += 1
    user_premium.coupon_id = maxcoupon
    user_premium.paid = false
    success = user_premium.save
    if success then
      redirect_to "https://www.CuentaDigital.com/api.php?id=573194&precio=100,00&venc=10&codigo=#{maxcoupon}&desde=premium@couchinn.com&hacia=#{current_user.email}&concepto=Un mes de premium en CouchInn (ID#{maxcoupon})&site=couchinn.com"
    else
      redirect_to user_premium_path , alert: "Error"
    end
  end
end

Web/app/views/user_premium/getpaidform.html.erb
<div class="authform">
	<h3>Ingresos</h3>

	<%= form_tag(getpaid_path, method: "post") do %>
	<div class="form-group">
		<%= label_tag(:start_date, "Fecha inicio") %>
		<%= date_field(:dates, :start_date, class: "form-control") %>
	</div>	
    
    <div class="form-group">
		<%= label_tag(:end_date, "Fecha fin") %>
		<%= date_field(:dates, :end_date, class: "form-control") %>
	</div>

	<%= submit_tag 'Calcular Ingresos', :class => 'button right' %>
	<% end %>
</div>

Web/app/views/user_premium/index.html.erb
<div class="authform">
	<h3>Usuario Premium</h3>

	<%= form_tag(user_premium_index_path, method: "post") do %>
    <% if current_user.is_premium? then %>
      <p><b>Ya eres usuario premium!</b> Tu suscripción vencerá en la siguiente fecha</p>
	  <div class="form-group">
	 	<label>Vencimiento</label>
		<input class="form-control" disabled="disabled" type="text" value="<%= current_user.premium_expiration%>" />
  	  </div>
      <p>Si lo deseas puedes agregar un mes a tu fecha de vencimiento por tan solo $100</p>
      <p>Ser usuario premium proriza tus publicaciones sobre las demás, y mostrará una miniatura con la foto de tus publicaciones en el listado</p>
    <% else %>
	  <p>Puedes convertirte en usuario premium a tan solo $100 por mes</p>
	  <p>Esto priorizará tus publicaciones sobre las demás, y mostrará una miniatura con la foto de tus publicaciones en el listado</p>
    <% end %>

	<p>Puedes efectuar el pago a través de Pago Facil, RapiPago, y otras sucursales adheridas.</p>
	<div class="form-group">
	  <label>Costo mensual</label>
	  <input class="form-control" disabled="disabled" type="text" value="$100" />
	</div>

    <% if current_user.is_premium? then %>
      <%= submit_tag 'Extender mi suscripción', :class => 'button right' %>
    <% else %>
      <%= submit_tag 'Convertirme en Premium', :class => 'button right' %>
    <% end %>
	<% end %>
</div>

Web/app/views/user_premium/setpaidform.html.erb
<div class="authform">
	<h3>Marcar boleta como paga</h3>

	<%= form_tag(setpaid_path, method: "post") do %>
	<div class="form-group">
		<%= label_tag(:id, "ID de la boleta") %>
		<%= text_field_tag(:id, "", class: 'form-control') %>
	</div>

	<%= submit_tag 'Marcar Paga', :class => 'button right' %>
	<% end %>
</div>